version: '3'
services:
  region-service:
    image: christiancavuti/region-service
    container_name: regions-service-container
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: python wsgi.py
    volumes:
      - ./:/app
    env_file:
      - ./.env
    environment:
      - LOGGING_DIR=/var/log/region-service/region-service.log
    ports:
      - "8000:8000"
    networks:
      - regions-network
    depends_on:
      - db
  db:
    image: postgres:13.1-alpine
    container_name: regions-db
    environment:
      - "POSTGRES_USER=${DATABASE_USER}"
      - "POSTGRES_PASSWORD=${DATABASE_PASSWORD}"
      - "POSTGRES_DB=postgres"
    volumes:
      - regions-volume:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - regions-network

volumes:
  regions-volume:
    driver: local

networks:
  regions-network:
    driver: bridge