"""region adjustments

Revision ID: bcc2538d3410
Revises: 
Create Date: 2021-03-10 22:25:22.649088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc2538d3410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('region', sa.Column('active', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'region', ['description'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'region', type_='unique')
    op.drop_column('region', 'active')
    # ### end Alembic commands ###
