name: Test and publish

on:
  push:
    tags:
    - "*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9.2
          architecture: x64
      - name: Checkout the code
        uses: actions/checkout@v2.3.4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Execute tests
        run: cd region_service/tests && pytest
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Get tag name
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Docker Login
        uses: docker/login-action@v1.8.0
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true
      - name: Docker Build
        run: docker build -t region-service .
      - name: Docker Tag
        run: docker tag region-service ${{ secrets.DOCKERHUB_USER }}/region-service:${{ steps.vars.outputs.tag }}
      - name: Docker Push
        run: docker push ${{ secrets.DOCKERHUB_USER }}/region-service
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
